#!/bin/sh

if [ "$1" = "" ]; then
  echo "Usage: kshell <pod>"
  exit 1
fi
POD=$1
shift

COLUMNS=`tput cols`
LINES=`tput lines`
TERM=xterm
CMD=$@
CMD=${CMD:-bash}
kubectl exec -i -t $POD -- env COLUMNS=$COLUMNS LINES=$LINES TERM=$TERM "$CMD"
